/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MarrePredictionHarmonique;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        String classUnderTest = new String();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.length() == 0);
    }
}
